version: "3.6"

services:
  speedcamera:
    build:
      context: .
    volumes:
      - "${PWD}/speedcamera:/app"
      - "${PWD}/photos:/photos"
    command: python3 /app/app.py
    privileged: true
